# Generated by Django 4.1.6 on 2023-06-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_coordonateur',
            new_name='is_gestionnaire',
        ),
    ]
