# Generated by Django 4.1.6 on 2023-06-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_visitor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_visiteur',
            field=models.BooleanField(default=False),
        ),
    ]
